#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

passer_livraison:
    path: /passerLivraison/{id}
    controller: App\Controller\CommandeController::passerLivraison
    methods: ['GET', 'POST']

